##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.11.2] date: [Tue Jul 06 19:12:54 CST 2021] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

.PHONY:$(MODULES) flash

######################################
# target
######################################
TARGET = graph

######################################
# module
######################################
MODULES := Graph

#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

#######################################
# module
#######################################
# single module build
MOD_CFG := module-cfg.mk
MOD_CMD := module-cmd.mk
MOD_RULE := module-rule.mk
MODULE_LIB := $(addsuffix .a, $(MODULES))
MODULE_LIB := $(addprefix $(DIR_BUILD)/lib, $(MODULE_LIB))

define compile_module
	cd $1 && $(MAKE) \
        DEBUG:=$(DEBUG) \
        BUILD_DIR:=$(abspath $(BUILD_DIR)) \
        MOD_CFG:=$(abspath $(MOD_CFG)) \
        MOD_RULE:=$(abspath $(MOD_RULE)) \
        MOD_CMD:=$(abspath $(MOD_CMD)) \
        && cd .. ;
endef

$(MODULE_LIB) : $(MODULES)

$(MODULES): $(BUILD_DIR) $(BUILD_DIR)/$(MAKECMDGOALS)
	@$(call compile_module, $@)

$(BUILD_DIR)/$(MAKECMDGOALS):
	mkdir $@

$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
