include $(MODULE_CFG)

SRC_DIR := .
INC_DIR := . $(INTERFACE_INC) $(COMMON_INC_DIR)

# ifneq ("$(COMMON_INC_DIR)","")
# INC_DIR += $(COMMON_INC_DIR)
# endif

# TYPE_INC := .h
# TYPE_SRC := .c
# TYPE_OBJ := .o 
# TYPE_DEP := .dep 

include $(MODULE_CMD)
include $(MODULE_RULE)